version: '3.9'

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: nsdgvjklosngojwsn

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql-data:
    driver: local