version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=iklhjfgsiowa
      - POSTGRES_USER=user

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8001:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: sdfrhewherwhgerwh


volumes:
  postgres-data:
    driver: local